### ISSUE TITLE
Build BWC

### ISSUE THREAD

**Issue by abdfnx** [abdfnx/botway#124]
# Botway Core (BWC)

> botway core is a self-hosted bot manager anyone can use it, it's depending on `bwc-api`, `bwc-app` and `bw-runner`

## Tasks

- [ ] Update `botway init` command to init `~/.botway/bwdb.json` file
- [ ] Build @botwayorg/bwc repo
- [ ] Make it a template
- [ ] Build `bwc-api`
   - [ ] Create database handler
   - [ ] Build controllers
   - [ ] Finish from **bwc-api-middleware**
   - [ ] Create `server.ts`
- [ ] Build `bwc-app`
   - [ ] Connect with `bwc-api`
   - [ ] Build login handler
   - [ ] Build Dashboard
   - [ ] Connect with `bwc-runner`
- [ ] Build `bwc-runner`
